/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectIdeasRouteImport } from './routes/projectIdeas'
import { Route as IndexRouteImport } from './routes/index'

const ProjectIdeasRoute = ProjectIdeasRouteImport.update({
  id: '/projectIdeas',
  path: '/projectIdeas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projectIdeas': typeof ProjectIdeasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projectIdeas': typeof ProjectIdeasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projectIdeas': typeof ProjectIdeasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projectIdeas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projectIdeas'
  id: '__root__' | '/' | '/projectIdeas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectIdeasRoute: typeof ProjectIdeasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projectIdeas': {
      id: '/projectIdeas'
      path: '/projectIdeas'
      fullPath: '/projectIdeas'
      preLoaderRoute: typeof ProjectIdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectIdeasRoute: ProjectIdeasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
